CREATE TABLE "t_event" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "id_individual" bigint NOT NULL,
  "date_time" timestamp NOT NULL,
  "geom" geometry NOT NULL,
  "id_nomencl_type" int,
  "id_observer" bigint,
  "media" text,
  "notes" text,
  "specific_details" json
);

CREATE TABLE "t_individual" (
  "id" bigint PRIMARY KEY NOT NULL,
  "cdnom" bigint NOT NULL,
  "sex" json NOT NULL,
  "name" text,
  "presumed_birth" int NOT NULL,
  "specific_details" json
);

CREATE TABLE "t_marking" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "id_event" uuid NOT NULL,
  "id_nomencl_type" int NOT NULL,
  "code" text NOT NULL,
  "id_nomencl_loc" int NOT NULL
);

CREATE TABLE "t_transmitter" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_event" uuid NOT NULL,
  "material" text NOT NULL,
  "state" bool NOT NULL,
  "id_nomencl_loc" int NOT NULL
);

CREATE TABLE "t_capture" (
  "id_event" uuid PRIMARY KEY NOT NULL,
  "id_nomencl_type" int,
  "notes" text,
  "specific_details" json
);

CREATE TABLE "t_sampling" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_event" uuid NOT NULL,
  "type" integer NOT NULL,
  "id_nomencl_preservation" integer,
  "id_nomencl_analysis_type" integer,
  "labo_receipt_date" date,
  "id_nomencl_labo_name" int,
  "labo_ref" text,
  "specific_results" json NOT NULL
);

CREATE TABLE "t_nomenclature" (
  "id" int NOT NULL,
  "short_name" text NOT NULL,
  "long_name" text NOT NULL
);

COMMENT ON COLUMN "t_event"."id_nomencl_type" IS 'Observation visuelle, capture, geoloc, piège photo ...';

COMMENT ON COLUMN "t_event"."specific_details" IS 'lieu-dit, dyspnee, jetage, kerato, toux,état physiologique, ...';

COMMENT ON COLUMN "t_individual"."specific_details" IS 'population, sous-population';

COMMENT ON COLUMN "t_transmitter"."state" IS '0=off, 1=on';

COMMENT ON COLUMN "t_capture"."id_nomencl_type" IS 'Filet, tir, cage ...';

COMMENT ON COLUMN "t_capture"."specific_details" IS 'température, poids, rythme cardiaque, résultat écho ...';

COMMENT ON COLUMN "t_sampling"."type" IS 'sang, déjection, plume, poil, cadavre ...';

COMMENT ON COLUMN "t_sampling"."id_nomencl_preservation" IS 'frais, frigo, congélateur, ...';

COMMENT ON COLUMN "t_sampling"."id_nomencl_analysis_type" IS 'coprologie, autopsie, génétique, sérologie, gestation ...';

ALTER TABLE "t_event" ADD CONSTRAINT "fk_t_event_t_individual" FOREIGN KEY ("id_individual") REFERENCES "t_individual" ("id");

ALTER TABLE "t_marking" ADD CONSTRAINT "fk_t_marking_t_event" FOREIGN KEY ("id_event") REFERENCES "t_event" ("id");

ALTER TABLE "t_transmitter" ADD CONSTRAINT "fk_t_transmitter_t_event" FOREIGN KEY ("id_event") REFERENCES "t_event" ("id");

ALTER TABLE "t_capture" ADD FOREIGN KEY ("id_event") REFERENCES "t_event" ("id");

ALTER TABLE "t_sampling" ADD CONSTRAINT "fk_t_sampling_t_event" FOREIGN KEY ("id_event") REFERENCES "t_event" ("id");
