CREATE TABLE "t_event" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "date_time" timestamp NOT NULL,
  "geom" geometry NOT NULL,
  "id_nomencl_type" int,
  "nb_individuals" int NOT NULL,
  "media" text,
  "notes" text,
  "specific_details" json
);

CREATE TABLE "t_individual" (
  "id" bigint PRIMARY KEY NOT NULL,
  "cd_nom" bigint NOT NULL,
  "sex" json NOT NULL,
  "name" text,
  "presumed_birth" int NOT NULL,
  "specific_details" json
);

CREATE TABLE "t_interaction" (
  "id_event" bigint NOT NULL,
  "id_individual_1" bigint NOT NULL,
  "id_individual_2" bigint NOT NULL,
  "id_nomencl_type" int NOT NULL,
  "id_nomencl_ground_type" int,
  "notes" text,
  PRIMARY KEY ("id_event", "id_individual_1", "id_individual_2")
);

CREATE TABLE "cor_event_individual" (
  "id_event" uuid NOT NULL,
  "id_individual" bigint NOT NULL,
  PRIMARY KEY ("id_event", "id_individual")
);

CREATE TABLE "cor_event_observer" (
  "id_event" uuid NOT NULL,
  "id_observer" bigint NOT NULL,
  PRIMARY KEY ("id_event", "id_observer")
);

CREATE TABLE "t_observer" (
  "id" bigint PRIMARY KEY NOT NULL
);

CREATE TABLE "t_marking" (
  "id_individual" bigint NOT NULL,
  "id_event" uuid NOT NULL,
  "id" int NOT NULL,
  "id_nomencl_type" int NOT NULL,
  "code" text NOT NULL,
  "id_nomencl_loc" int NOT NULL,
  PRIMARY KEY ("id_individual", "id_event", "id")
);

CREATE TABLE "t_transmitter" (
  "id" int PRIMARY KEY NOT NULL,
  "brand" text NOT NULL,
  "material" text NOT NULL,
  "state" bool NOT NULL,
  "details" json
);

CREATE TABLE "t_transmitter_indiv" (
  "id_transmitter" int NOT NULL,
  "id_individual" bigint NOT NULL,
  "id_event" uuid NOT NULL,
  "id_nomencl_loc" int NOT NULL,
  "state" bool NOT NULL,
  PRIMARY KEY ("id_transmitter", "id_individual")
);

CREATE TABLE "t_capture" (
  "id_individual" bigint NOT NULL,
  "id_event" uuid NOT NULL,
  "id_nomencl_type" int,
  "notes" text,
  "specific_details" json,
  PRIMARY KEY ("id_individual", "id_event")
);

CREATE TABLE "t_sampling" (
  "id_individual" bigint NOT NULL,
  "id_event" uuid NOT NULL,
  "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "type" integer NOT NULL,
  "id_nomencl_preservation" integer,
  "id_nomencl_analysis_type" integer,
  "labo_receipt_date" date,
  "id_nomencl_labo_name" int,
  "labo_ref" text,
  "specific_results" json NOT NULL,
  PRIMARY KEY ("id_individual", "id_event", "id")
);

CREATE TABLE "t_taxonomy" (
  "cd_nom" int NOT NULL
);

CREATE TABLE "t_nomenclature" (
  "id" int NOT NULL,
  "short_name" text NOT NULL,
  "long_name" text NOT NULL
);

COMMENT ON COLUMN "t_event"."id_nomencl_type" IS 'Observation visuelle, capture, geoloc, piège photo ...';

COMMENT ON COLUMN "t_event"."specific_details" IS 'lieu-dit, classe d âge, dyspnee, jetage, kerato, toux,état physiologique, données gps...';

COMMENT ON COLUMN "t_individual"."specific_details" IS 'population, sous-population';

COMMENT ON COLUMN "t_transmitter"."state" IS '0=off, 1=on';

COMMENT ON COLUMN "t_transmitter_indiv"."state" IS '0=off, 1=on';

COMMENT ON COLUMN "t_capture"."id_nomencl_type" IS 'Filet, tir, cage ...';

COMMENT ON COLUMN "t_capture"."specific_details" IS 'température, poids, rythme cardiaque, résultat écho ...';

COMMENT ON COLUMN "t_sampling"."type" IS 'sang, déjection, plume, poil, cadavre ...';

COMMENT ON COLUMN "t_sampling"."id_nomencl_preservation" IS 'frais, frigo, congélateur, ...';

COMMENT ON COLUMN "t_sampling"."id_nomencl_analysis_type" IS 'coprologie, autopsie, génétique, sérologie, gestation ...';

ALTER TABLE "t_individual" ADD CONSTRAINT "fk_t_individual_t_taxonomie" FOREIGN KEY ("cd_nom") REFERENCES "t_taxonomy" ("cd_nom");

ALTER TABLE "cor_event_individual" ADD CONSTRAINT "fk_t_interaction_cor_event_indiv1" FOREIGN KEY ("id_event", "id_individual") REFERENCES "t_interaction" ("id_event", "id_individual_1");

ALTER TABLE "cor_event_individual" ADD CONSTRAINT "fk_t_interaction_cor_event_indiv2" FOREIGN KEY ("id_event", "id_individual") REFERENCES "t_interaction" ("id_event", "id_individual_2");

ALTER TABLE "cor_event_individual" ADD CONSTRAINT "fk_cor_event_indiv_t_event" FOREIGN KEY ("id_event") REFERENCES "t_event" ("id");

ALTER TABLE "cor_event_individual" ADD CONSTRAINT "fk_cor_event_indiv_t_individual" FOREIGN KEY ("id_individual") REFERENCES "t_individual" ("id");

ALTER TABLE "cor_event_observer" ADD CONSTRAINT "fk_cor_event_obs_t_event" FOREIGN KEY ("id_event") REFERENCES "t_event" ("id");

ALTER TABLE "cor_event_observer" ADD CONSTRAINT "fk_cor_event_obs_t_observer" FOREIGN KEY ("id_observer") REFERENCES "t_observer" ("id");

ALTER TABLE "t_marking" ADD CONSTRAINT "fk_t_marking_t_individual" FOREIGN KEY ("id_individual") REFERENCES "t_individual" ("id");

ALTER TABLE "t_marking" ADD CONSTRAINT "fk_t_marking_t_event" FOREIGN KEY ("id_event") REFERENCES "t_event" ("id");

ALTER TABLE "t_transmitter_indiv" ADD CONSTRAINT "fk_t_transmitter_indiv_t_event" FOREIGN KEY ("id_event") REFERENCES "t_event" ("id");

ALTER TABLE "t_transmitter_indiv" ADD CONSTRAINT "fk_t_transmitter_indiv_t_individual" FOREIGN KEY ("id_individual") REFERENCES "t_individual" ("id");

ALTER TABLE "t_transmitter_indiv" ADD CONSTRAINT "fk_t_transmitter_indiv_t_transmitter" FOREIGN KEY ("id_transmitter") REFERENCES "t_transmitter" ("id");

ALTER TABLE "t_capture" ADD CONSTRAINT "fk_t_capture_t_event" FOREIGN KEY ("id_event") REFERENCES "t_event" ("id");

ALTER TABLE "t_capture" ADD CONSTRAINT "fk_t_capture_t_individual" FOREIGN KEY ("id_individual") REFERENCES "t_individual" ("id");

ALTER TABLE "t_sampling" ADD CONSTRAINT "fk_t_sampling_t_event" FOREIGN KEY ("id_event") REFERENCES "t_event" ("id");

ALTER TABLE "t_sampling" ADD CONSTRAINT "fk_t_sampling_t_individual" FOREIGN KEY ("id_individual") REFERENCES "t_individual" ("id");
